title: "Michael Tueting"
author: "Michael Tueting"
description: "University of St.Gallen"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header
enable_dark_mode: true    # disable dark mode

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "CV", file: "CV.md"}
  - {title: "Test", url: "https://mtueting.github.io/t_ting_cv__Copy.pdf"}
  - {title: "Blog", file: "blog.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:michael.tueting@unisg.ch"}
  - {title: Github, icon: github, url: "https://github.com/MTueting"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
